#############################################################################
# Makefile for building: Musvi.app/Contents/MacOS/Musvi
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  musvi.pro
# Template: app
# Command: /Users/Eva/Qt5.9.4/5.9.4/clang_64/bin/qmake -o Makefile musvi.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -F/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib
QMAKE         = /Users/Eva/Qt5.9.4/5.9.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Eva/Qt5.9.4/5.9.4/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Eva/Qt5.9.4/5.9.4/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Musvi1.0.0
DISTDIR = /Users/Eva/QT-PROJECTS/MUSVI/.tmp/Musvi1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtMultimedia -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		logic.cpp \
		bufferprocessor.cpp \
		classifier.cpp \
		filter.cpp \
		highpassfilter.cpp \
		impulse.cpp \
		lowpassfilter.cpp \
		transcriptor.cpp \
		metronomethread.cpp \
		scoresaver.cpp \
		calibrator.cpp qrc_ressources.cpp \
		moc_logic.cpp \
		moc_transcriptor.cpp
OBJECTS       = main.o \
		logic.o \
		bufferprocessor.o \
		classifier.o \
		filter.o \
		highpassfilter.o \
		impulse.o \
		lowpassfilter.o \
		transcriptor.o \
		metronomethread.o \
		scoresaver.o \
		calibrator.o \
		qrc_ressources.o \
		moc_logic.o \
		moc_transcriptor.o
DIST          = config/config.ini \
		qml/ArtistMode.qml \
		qml/Menu.qml \
		qml/Information.qml \
		qml/Init.qml \
		qml/Musvi_Controller \
		qml/Practice.qml \
		qml/PopUp.qml \
		main.qml \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf \
		musvi.pro logic.h \
		bufferprocessor.h \
		classifier.h \
		filter.h \
		highpassfilter.h \
		impulse.h \
		lowpassfilter.h \
		transcriptor.h \
		metronomethread.h \
		scoresaver.h \
		calibrator.h main.cpp \
		logic.cpp \
		bufferprocessor.cpp \
		classifier.cpp \
		filter.cpp \
		highpassfilter.cpp \
		impulse.cpp \
		lowpassfilter.cpp \
		transcriptor.cpp \
		metronomethread.cpp \
		scoresaver.cpp \
		calibrator.cpp
QMAKE_TARGET  = Musvi
DESTDIR       = 
TARGET        = Musvi.app/Contents/MacOS/Musvi

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d Musvi.app/Contents/MacOS/ || mkdir -p Musvi.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: musvi.pro ../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf \
		musvi.pro \
		ressources.qrc \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/QtQml.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile musvi.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf:
musvi.pro:
ressources.qrc:
../../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/QtQml.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile musvi.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

Musvi.app/Contents/PkgInfo: 
	@test -d Musvi.app/Contents || mkdir -p Musvi.app/Contents
	@$(DEL_FILE) Musvi.app/Contents/PkgInfo
	@echo "APPL????" > Musvi.app/Contents/PkgInfo
Musvi.app/Contents/Resources/empty.lproj: 
	@test -d Musvi.app/Contents/Resources || mkdir -p Musvi.app/Contents/Resources
	@touch Musvi.app/Contents/Resources/empty.lproj
	
Musvi.app/Contents/Info.plist: 
	@test -d Musvi.app/Contents || mkdir -p Musvi.app/Contents
	@$(DEL_FILE) Musvi.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Eva.Musvi,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Musvi,g" -e "s,@LIBRARY@,Musvi,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/Info.plist.app >Musvi.app/Contents/Info.plist

all: Makefile \
		Musvi.app/Contents/PkgInfo \
		Musvi.app/Contents/Resources/empty.lproj \
		Musvi.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ressources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents logic.h bufferprocessor.h classifier.h filter.h highpassfilter.h impulse.h lowpassfilter.h transcriptor.h metronomethread.h scoresaver.h calibrator.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp logic.cpp bufferprocessor.cpp classifier.cpp filter.cpp highpassfilter.cpp impulse.cpp lowpassfilter.cpp transcriptor.cpp metronomethread.cpp scoresaver.cpp calibrator.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Musvi.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_ressources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ressources.cpp
qrc_ressources.cpp: ressources.qrc \
		../../Qt5.9.4/5.9.4/clang_64/bin/rcc \
		main.qml \
		qml/Menu.qml \
		qml/PopUp.qml \
		qml/ArtistMode.qml \
		qml/Information.qml \
		qml/Init.qml \
		qml/Musvi_Controller.qml \
		qml/Practice.qml \
		images/negra.png \
		images/1110.png \
		images/1010.png \
		images/1111.png \
		images/negra-silencio.png \
		images/1011.png \
		images/corchea.png \
		images/0110.png \
		images/1100.png \
		images/0010.png \
		images/0111.png \
		images/1000.png \
		images/1101.png \
		images/0011.png \
		images/1001.png \
		images/bar.png \
		images/semicorcheas.png \
		images/corcheas.png \
		images/0100.png \
		images/0000.png \
		images/0101.png \
		images/0001.png \
		images/partitura-practice.png \
		images/semicorchea-silencio.png \
		images/blanca.png \
		images/corche-semi.png \
		images/line.png \
		images/popupConfig/slider.png \
		images/popupConfig/botonCancel.png \
		images/popupConfig/sliderColor.png \
		images/popupConfig/botonSlider.png \
		images/popupConfig/selectorCompas.png \
		images/popupConfig/bgConfig.png \
		images/popupConfig/closePopup.png \
		images/popupConfig/botonChange.png \
		images/artist/count1.png \
		images/artist/count3.png \
		images/artist/score.png \
		images/artist/count2.png \
		images/artist/settings.png \
		images/calibrate/textCalibrate.png \
		images/calibrate/calibrate.gif \
		images/calibrate/bgCalibrate.png \
		images/menu/stop.png \
		images/menu/botonInfo.png \
		images/menu/botonConfig.png \
		images/menu/start.png \
		images/menu/bgMenu.png \
		images/menu/init.png \
		images/menu/info.png \
		images/init/selectMode.png \
		images/init/bgModeArtist.png \
		images/init/bgModePractice.png \
		sounds/beat.wav \
		fonts/gotham/GothamLight.ttf \
		fonts/gotham/GothamBook.ttf
	/Users/Eva/Qt5.9.4/5.9.4/clang_64/bin/rcc -name ressources ressources.qrc -o qrc_ressources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_logic.cpp moc_transcriptor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_logic.cpp moc_transcriptor.cpp
moc_logic.cpp: ../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		transcriptor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		metronomethread.h \
		bufferprocessor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		impulse.h \
		classifier.h \
		lowpassfilter.h \
		filter.h \
		highpassfilter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		scoresaver.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		calibrator.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/QAudioInput \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/qaudioinput.h \
		logic.h \
		moc_predefs.h \
		../../Qt5.9.4/5.9.4/clang_64/bin/moc
	/Users/Eva/Qt5.9.4/5.9.4/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -I/Users/Eva/QT-PROJECTS/MUSVI -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include -F/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib logic.h -o moc_logic.cpp

moc_transcriptor.cpp: ../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		metronomethread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qthread.h \
		bufferprocessor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		impulse.h \
		classifier.h \
		lowpassfilter.h \
		filter.h \
		highpassfilter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		scoresaver.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		calibrator.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/QAudioInput \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/qaudioinput.h \
		transcriptor.h \
		moc_predefs.h \
		../../Qt5.9.4/5.9.4/clang_64/bin/moc
	/Users/Eva/Qt5.9.4/5.9.4/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -I/Users/Eva/QT-PROJECTS/MUSVI -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include -F/Users/Eva/Qt5.9.4/5.9.4/clang_64/lib transcriptor.h -o moc_transcriptor.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		logic.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		transcriptor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		metronomethread.h \
		bufferprocessor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		impulse.h \
		classifier.h \
		lowpassfilter.h \
		filter.h \
		highpassfilter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		scoresaver.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		calibrator.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/QAudioInput \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/qaudioinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

logic.o: logic.cpp logic.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		transcriptor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		metronomethread.h \
		bufferprocessor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		impulse.h \
		classifier.h \
		lowpassfilter.h \
		filter.h \
		highpassfilter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		scoresaver.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		calibrator.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/QAudioInput \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/qaudioinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logic.o logic.cpp

bufferprocessor.o: bufferprocessor.cpp bufferprocessor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		impulse.h \
		classifier.h \
		lowpassfilter.h \
		filter.h \
		highpassfilter.h \
		logic.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaEnum \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QMetaObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		transcriptor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		metronomethread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		scoresaver.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		calibrator.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/QAudioInput \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/qaudioinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bufferprocessor.o bufferprocessor.cpp

classifier.o: classifier.cpp classifier.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		impulse.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classifier.o classifier.cpp

filter.o: filter.cpp filter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filter.o filter.cpp

highpassfilter.o: highpassfilter.cpp highpassfilter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highpassfilter.o highpassfilter.cpp

impulse.o: impulse.cpp impulse.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o impulse.o impulse.cpp

lowpassfilter.o: lowpassfilter.cpp lowpassfilter.h \
		filter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lowpassfilter.o lowpassfilter.cpp

transcriptor.o: transcriptor.cpp transcriptor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		metronomethread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qthread.h \
		bufferprocessor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		impulse.h \
		classifier.h \
		lowpassfilter.h \
		filter.h \
		highpassfilter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		scoresaver.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		calibrator.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/QAudioInput \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/qaudioinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transcriptor.o transcriptor.cpp

metronomethread.o: metronomethread.cpp metronomethread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metronomethread.o metronomethread.cpp

scoresaver.o: scoresaver.cpp scoresaver.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QStandardPaths \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scoresaver.o scoresaver.cpp

calibrator.o: calibrator.cpp calibrator.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/QAudioInput \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtMultimedia.framework/Headers/qaudioinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrator.o calibrator.cpp

qrc_ressources.o: qrc_ressources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ressources.o qrc_ressources.cpp

moc_logic.o: moc_logic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logic.o moc_logic.cpp

moc_transcriptor.o: moc_transcriptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transcriptor.o moc_transcriptor.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/Users/Eva/QT-PROJECTS/MUSVI || mkdir -p $(INSTALL_ROOT)/Users/Eva/QT-PROJECTS/MUSVI
	$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Eva/QT-PROJECTS/MUSVI/Musvi.app
	
	-$(QINSTALL) Musvi.app $(INSTALL_ROOT)/Users/Eva/QT-PROJECTS/MUSVI/Musvi.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Eva/QT-PROJECTS/MUSVI/Musvi.app
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/Eva/QT-PROJECTS/MUSVI/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

