#############################################################################
# Makefile for building: interface
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  musvi.pro
# Template: aux
# Command: /Users/Eva/Qt5.9.4/5.9.4/ios/bin/qmake -o Makefile musvi.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) $(EXPORT_QMAKE_XARCH_CFLAGS) -fobjc-nonfragile-abi -fobjc-legacy-dispatch -fembed-bitcode-marker -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) $(EXPORT_QMAKE_XARCH_CFLAGS) -fobjc-nonfragile-abi -fobjc-legacy-dispatch -fembed-bitcode-marker -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit -I../../Qt5.9.4/5.9.4/ios/include -I../../Qt5.9.4/5.9.4/ios/include/QtQuick -I../../Qt5.9.4/5.9.4/ios/include/QtMultimedia -I../../Qt5.9.4/5.9.4/ios/include/QtWidgets -I../../Qt5.9.4/5.9.4/ios/include/QtGui -I../../Qt5.9.4/5.9.4/ios/include/QtQml -I../../Qt5.9.4/5.9.4/ios/include/QtNetwork -I../../Qt5.9.4/5.9.4/ios/include/QtCore -I. -I../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang
QMAKE         = /Users/Eva/Qt5.9.4/5.9.4/ios/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Eva/Qt5.9.4/5.9.4/ios/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Eva/Qt5.9.4/5.9.4/ios/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = interface1.0.0
DISTDIR = /Users/Eva/QT-PROJECTS/MUSVI/.tmp/interface1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ $(EXPORT_ARCH_ARGS) $(EXPORT_QMAKE_XARCH_LFLAGS) -fembed-bitcode-marker -Wl,-e,_qt_main_wrapper -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -L/Users/Eva/Qt5.9.4/5.9.4/ios/plugins/platforms -framework Foundation -framework UIKit -framework QuartzCore -framework AudioToolbox -framework AssetsLibrary -L/Users/Eva/Qt5.9.4/5.9.4/ios/lib -framework MobileCoreServices -framework CoreFoundation -framework CoreGraphics -framework OpenGLES -framework CoreText -L/Users/Eva/Qt5.9.4/5.9.4/ios/plugins/mediaservice -lqavfcamera -framework CoreAudio -framework CoreMedia -framework CoreVideo -framework Security -framework AVFoundation -lqavfmediaplayer -lQt5MultimediaWidgets -lQt5OpenGL -lqtmedia_audioengine -L/Users/Eva/Qt5.9.4/5.9.4/ios/plugins/audio -lqtaudio_coreaudio -L/Users/Eva/Qt5.9.4/5.9.4/ios/plugins/playlistformats -lqtmultimedia_m3u -lqios -lQt5FontDatabaseSupport -lqtfreetype -lQt5GraphicsSupport -lQt5ClipboardSupport -L/Users/Eva/Qt5.9.4/5.9.4/ios/plugins/imageformats -lqgif -lqicns -lqico -lqjpeg -lqmacjp2 -framework ImageIO -lqtga -lqtiff -lqwbmp -lqwebp -L/Users/Eva/Qt5.9.4/5.9.4/ios/plugins/qmltooling -lqmldbg_debugger -lqmldbg_inspector -lqmldbg_local -lqmldbg_messages -lqmldbg_native -lqmldbg_nativedebugger -lqmldbg_profiler -lqmldbg_quickprofiler -lqmldbg_server -lQt5PacketProtocol -lqmldbg_tcp -L/Users/Eva/Qt5.9.4/5.9.4/ios/plugins/bearer -lqgenericbearer -lQt5Multimedia -lQt5Widgets -L/Users/Eva/Qt5.9.4/5.9.4/ios/qml/QtQuick.2 -lqtquick2plugin -L/Users/Eva/Qt5.9.4/5.9.4/ios/qml/QtQuick/Controls.2 -lqtquickcontrols2plugin -lQt5QuickControls2 -L/Users/Eva/Qt5.9.4/5.9.4/ios/qml/QtQuick/Layouts -lqquicklayoutsplugin -L/Users/Eva/Qt5.9.4/5.9.4/ios/qml/QtQuick/Window.2 -lwindowplugin -L/Users/Eva/Qt5.9.4/5.9.4/ios/qml/QtQuick/Templates.2 -lqtquicktemplates2plugin -lQt5QuickTemplates2 -lQt5Quick -lQt5Gui -lqtlibpng -lqtharfbuzz -lQt5Qml -lQt5Network -lQt5Core -lm -lz -lqtpcre2 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =  /Users/Eva/QT-PROJECTS/MUSVI/interface_plugin_import.cpp \
		/Users/Eva/QT-PROJECTS/MUSVI/interface_qml_plugin_import.cpp
OBJECTS       = interface_plugin_import.o \
		interface_qml_plugin_import.o
DIST          = config/config.ini \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/spec_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/qdevice.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/device_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/unix.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/mac.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/ios.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/sanitize.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/gcc-base.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/clang.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/clang-mac.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit/clang.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit/qmake.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/qconfig.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt_functions.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/exclusive_builds.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/sdk.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/sdk.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/toolchain.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/toolchain.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/default_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/default_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/default_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/resolve_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/resolve_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/exclusive_builds_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/exclusive_builds_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/objective_c.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qml_debug.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/bitcode.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/warn_on.prf \
		../../Qt5.9.4/5.9.4/ios/plugins/platforms/libqios.prl \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/qt.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/resources.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/moc.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/unix/opengl.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uic.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/unix/thread.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qmake_use.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/file_copies.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/rez.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/testcase_targets.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/exceptions.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/yacc.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/lex.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/xcodebuild.prf \
		musvi.pro logic.h 
QMAKE_TARGET  = interface
DESTDIR       = 
TARGET        = interface
TARGETA       = 
TARGET0       = 
TARGETD       = 
TARGET1       = 
TARGET2       = 

####### Custom Variables
EXPORT_QMAKE_XARCH_CFLAGS_x86_64 = -Xarch_x86_64 -mios-simulator-version-min=8.0 -Xarch_x86_64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_QMAKE_XARCH_LFLAGS = $(EXPORT_QMAKE_XARCH_LFLAGS_armv7) $(EXPORT_QMAKE_XARCH_LFLAGS_arm64) $(EXPORT_QMAKE_XARCH_LFLAGS_i386) $(EXPORT_QMAKE_XARCH_LFLAGS_x86_64)
EXPORT_SUBTARGETS = debug-device debug-simulator release-device release-simulator
EXPORT_QMAKE_XARCH_LFLAGS_i386 = -Xarch_i386 -mios-simulator-version-min=8.0 -Xarch_i386 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk
EXPORT_QMAKE_XARCH_CFLAGS_arm64 = -Xarch_arm64 -miphoneos-version-min=8.0 -Xarch_arm64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
EXPORT_QMAKE_XARCH_LFLAGS_arm64 = -Xarch_arm64 -miphoneos-version-min=8.0 -Xarch_arm64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
EXPORT_QMAKE_XARCH_LFLAGS_x86_64 = -Xarch_x86_64 -mios-simulator-version-min=8.0 -Xarch_x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk
EXPORT_DEVICE_FILTER = iPhone|iPad
EXPORT_QMAKE_XARCH_CFLAGS_armv7 = -Xarch_armv7 -miphoneos-version-min=8.0 -Xarch_armv7 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
EXPORT_QMAKE_XARCH_CFLAGS_i386 = -Xarch_i386 -mios-simulator-version-min=8.0 -Xarch_i386 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk
EXPORT_GENERIC_DEVICE_DESTINATION = generic/platform=iOS
EXPORT_QMAKE_XARCH_LFLAGS_armv7 = -Xarch_armv7 -miphoneos-version-min=8.0 -Xarch_armv7 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
EXPORT_SIMULATOR_SDK = iphonesimulator
EXPORT_DEVICE_SDK = iphoneos
EXPORT_VALID_ARCHS = armv7 arm64 i386 x86_64
EXPORT_QMAKE_XARCH_CFLAGS = $(EXPORT_QMAKE_XARCH_CFLAGS_armv7) $(EXPORT_QMAKE_XARCH_CFLAGS_arm64) $(EXPORT_QMAKE_XARCH_CFLAGS_i386) $(EXPORT_QMAKE_XARCH_CFLAGS_x86_64)
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /Users/Eva/Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/xcodebuild.mk
first:
####### Build rules

$(TARGET): /Users/Eva/Qt5.9.4/5.9.4/ios/lib/libQt5Quick.a /Users/Eva/Qt5.9.4/5.9.4/ios/lib/libQt5Multimedia.a /Users/Eva/Qt5.9.4/5.9.4/ios/lib/libQt5Widgets.a /Users/Eva/Qt5.9.4/5.9.4/ios/lib/libQt5Gui.a /Users/Eva/Qt5.9.4/5.9.4/ios/lib/libQt5Qml.a /Users/Eva/Qt5.9.4/5.9.4/ios/lib/libQt5Network.a /Users/Eva/Qt5.9.4/5.9.4/ios/lib/libQt5Core.a $(OBJECTS)  
	

Makefile: musvi.pro ../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang/qmake.conf ../../Qt5.9.4/5.9.4/ios/mkspecs/features/spec_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/qdevice.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/device_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/unix.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/mac.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/ios.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/sanitize.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/gcc-base.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/clang.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/clang-mac.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit/clang.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit/qmake.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/qconfig.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt_functions.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/exclusive_builds.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/sdk.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/sdk.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/toolchain.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/toolchain.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/default_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/default_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/default_pre.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/resolve_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/resolve_config.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/exclusive_builds_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/exclusive_builds_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/objective_c.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qml_debug.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/bitcode.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/warn_on.prf \
		../../Qt5.9.4/5.9.4/ios/plugins/platforms/libqios.prl \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/qt.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/resources.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/moc.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/unix/opengl.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uic.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/unix/thread.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/qmake_use.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/file_copies.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/rez.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/testcase_targets.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/exceptions.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/yacc.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/lex.prf \
		../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/xcodebuild.prf \
		musvi.pro \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5FontDatabaseSupport.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libqtfreetype.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5GraphicsSupport.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5ClipboardSupport.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5Gui.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libqtlibpng.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libqtharfbuzz.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5Core.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libqtpcre2.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/mediaservice/libqavfcamera.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/mediaservice/libqavfmediaplayer.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/mediaservice/libqtmedia_audioengine.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/audio/libqtaudio_coreaudio.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/playlistformats/libqtmultimedia_m3u.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqgif.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqicns.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqico.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqjpeg.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqmacjp2.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqtga.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqtiff.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqwbmp.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqwebp.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_debugger.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_inspector.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_local.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_messages.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_native.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_profiler.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_server.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_tcp.prl \
		../../Qt5.9.4/5.9.4/ios/plugins/bearer/libqgenericbearer.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5Quick.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5Multimedia.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5Widgets.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5Qml.prl \
		../../Qt5.9.4/5.9.4/ios/lib/libQt5Network.prl \
		../../Qt5.9.4/5.9.4/ios/qml/QtQuick.2/libqtquick2plugin.prl \
		../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.prl \
		../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl \
		../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Window.2/libwindowplugin.prl \
		../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.prl
	$(QMAKE) -o Makefile musvi.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
../../Qt5.9.4/5.9.4/ios/mkspecs/features/spec_pre.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/qdevice.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/device_config.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/unix.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/mac.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/ios.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/sanitize.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/gcc-base.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/gcc-base-mac.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/clang.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/clang-mac.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit/clang.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/common/uikit/qmake.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/qconfig.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_core.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_help.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_location.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_network.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_script.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qgif.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qicns.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qico.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qios.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtga.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/modules/qt_plugin_scene2d.pri:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt_functions.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt_config.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang/qmake.conf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/exclusive_builds.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/sdk.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/sdk.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/toolchain.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/toolchain.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/default_pre.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/default_pre.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/default_pre.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/resolve_config.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/resolve_config.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/exclusive_builds_post.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/exclusive_builds_post.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/default_post.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/default_post.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/default_post.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/objective_c.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/qml_debug.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/bitcode.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/warn_on.prf:
../../Qt5.9.4/5.9.4/ios/plugins/platforms/libqios.prl:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/qt.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/qt.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/resources.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/moc.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/unix/opengl.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uic.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/unix/thread.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/qmake_use.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/file_copies.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/rez.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/testcase_targets.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/exceptions.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/yacc.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/lex.prf:
../../Qt5.9.4/5.9.4/ios/mkspecs/features/uikit/xcodebuild.prf:
musvi.pro:
../../Qt5.9.4/5.9.4/ios/lib/libQt5FontDatabaseSupport.prl:
../../Qt5.9.4/5.9.4/ios/lib/libqtfreetype.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5GraphicsSupport.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5ClipboardSupport.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5Gui.prl:
../../Qt5.9.4/5.9.4/ios/lib/libqtlibpng.prl:
../../Qt5.9.4/5.9.4/ios/lib/libqtharfbuzz.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5Core.prl:
../../Qt5.9.4/5.9.4/ios/lib/libqtpcre2.prl:
../../Qt5.9.4/5.9.4/ios/plugins/mediaservice/libqavfcamera.prl:
../../Qt5.9.4/5.9.4/ios/plugins/mediaservice/libqavfmediaplayer.prl:
../../Qt5.9.4/5.9.4/ios/plugins/mediaservice/libqtmedia_audioengine.prl:
../../Qt5.9.4/5.9.4/ios/plugins/audio/libqtaudio_coreaudio.prl:
../../Qt5.9.4/5.9.4/ios/plugins/playlistformats/libqtmultimedia_m3u.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqgif.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqicns.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqico.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqjpeg.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqmacjp2.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqtga.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqtiff.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqwbmp.prl:
../../Qt5.9.4/5.9.4/ios/plugins/imageformats/libqwebp.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_debugger.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_inspector.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_local.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_messages.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_native.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_profiler.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_server.prl:
../../Qt5.9.4/5.9.4/ios/plugins/qmltooling/libqmldbg_tcp.prl:
../../Qt5.9.4/5.9.4/ios/plugins/bearer/libqgenericbearer.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5Quick.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5Multimedia.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5Widgets.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5Qml.prl:
../../Qt5.9.4/5.9.4/ios/lib/libQt5Network.prl:
../../Qt5.9.4/5.9.4/ios/qml/QtQuick.2/libqtquick2plugin.prl:
../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.prl:
../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl:
../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Window.2/libwindowplugin.prl:
../../Qt5.9.4/5.9.4/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile musvi.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) /Users/Eva/QT-PROJECTS/MUSVI/interface_plugin_import.cpp /Users/Eva/QT-PROJECTS/MUSVI/interface_qml_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

debug: debug-device debug-simulator

device: debug-device release-device

simulator: debug-simulator release-simulator

release: release-device release-simulator

mocclean:

mocables:

distclean: clean_all distclean_xcodebuild

distclean_xcodebuild:
	-$(DEL_FILE) -R interface.xcodeproj Debug-device Debug-simulator Release-device Release-simulator

compiler_clean: 

####### Compile

interface_plugin_import.o: /Users/Eva/QT-PROJECTS/MUSVI/interface_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interface_plugin_import.o /Users/Eva/QT-PROJECTS/MUSVI/interface_plugin_import.cpp

interface_qml_plugin_import.o: /Users/Eva/QT-PROJECTS/MUSVI/interface_qml_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interface_qml_plugin_import.o /Users/Eva/QT-PROJECTS/MUSVI/interface_qml_plugin_import.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

